name: Build wheel and sdist packages
on:
  push:
    tags:
      - v*.*.*
jobs:
  create_draft_release:
    name: Create a draft GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
          gh release create $TAG_NAME --draft
  build_wheels:
    needs: create_draft_release
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # skip windows-2019,
        os: [ubuntu-20.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_SKIP: cp36-* pp*
          CIBW_BEFORE_BUILD: pip install numpy scikit-learn "Cython>=3.0.0a10"
      - name: Upload wheel packages to a GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
          gh release upload $TAG_NAME ./wheelhouse/*.whl

  build_sdist:
    needs: create_draft_release
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --progress-bar off --upgrade pip setuptools
          pip install numpy scikit-learn "Cython>=3.0.0a10"

      - name: Build sdist
        run: |
          python setup.py build_ext --inplace
          python setup.py sdist

      - name: Upload a sdist package to a GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
          gh release upload $TAG_NAME ./dist/*.tar.gz
